Fans
Konzertabrechnungen 
CD
Konzerttickets 

Fans -- Konzerttickets  {
    source-arrowhead: M
    target-arrowhead: 1
}
Konzerttickets  -- Konzertabrechnungen {
    source-arrowhead: 1
    target-arrowhead: 1
}
Konzerttickets  -- CD {
    source-arrowhead: M
    target-arrowhead: M
}
